language: python
sudo: false
python:
  - "3.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - mkdir test-reports
  - py.test --junitxml=test-reports/results.xml --cov=./
  - bash <(curl -s https://codecov.io/bash)
